name: example
description: Showcase for material_async_button.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.1.0
  material_async_button:
    path: ../

dev_dependencies:
  checks: ^0.3.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
