part of '../../material_async_button.dart';

enum _FilledVariant { primary, tonal }

/// Async-aware [FilledButton] with all four Material 3 flavors:
/// [FilledAsyncButton.new], [FilledAsyncButton.tonal],
/// [FilledAsyncButton.icon], [FilledAsyncButton.tonalIcon].
class FilledAsyncButton extends AsyncStandardMaterialButton {
  const FilledAsyncButton({
    super.key,
    required super.onPressed,
    required super.child,
    super.onLongPress,
    super.onHover,
    super.onFocusChange,
    super.style,
    super.focusNode,
    super.autofocus,
    super.clipBehavior,
    super.statesController,
    super.controller,
    super.onSuccess,
    super.onError,
    super.onStateChanged,
    super.confirmBeforePress,
    super.loadingChild,
    super.successChild,
    super.errorChild,
    super.disabled,
    super.switchDuration,
    super.transitionBuilder,
    super.successDisplayDuration,
    super.errorDisplayDuration,
    super.cooldownDuration,
    super.animateSize,
    super.hapticOn,
    super.announceSemantics,
    super.rethrowErrors,
  }) : _variant = .primary;

  const FilledAsyncButton.tonal({
    super.key,
    required super.onPressed,
    required super.child,
    super.onLongPress,
    super.onHover,
    super.onFocusChange,
    super.style,
    super.focusNode,
    super.autofocus,
    super.clipBehavior,
    super.statesController,
    super.controller,
    super.onSuccess,
    super.onError,
    super.onStateChanged,
    super.confirmBeforePress,
    super.loadingChild,
    super.successChild,
    super.errorChild,
    super.disabled,
    super.switchDuration,
    super.transitionBuilder,
    super.successDisplayDuration,
    super.errorDisplayDuration,
    super.cooldownDuration,
    super.animateSize,
    super.hapticOn,
    super.announceSemantics,
    super.rethrowErrors,
  }) : _variant = .tonal;

  const FilledAsyncButton.icon({
    super.key,
    required super.onPressed,
    super.onLongPress,
    super.onHover,
    super.onFocusChange,
    super.style,
    super.focusNode,
    super.autofocus,
    super.clipBehavior,
    super.statesController,
    super.iconAlignment,
    super.controller,
    super.onSuccess,
    super.onError,
    super.onStateChanged,
    super.confirmBeforePress,
    super.loadingChild,
    super.successChild,
    super.errorChild,
    super.disabled,
    super.switchDuration,
    super.transitionBuilder,
    super.successDisplayDuration,
    super.errorDisplayDuration,
    super.cooldownDuration,
    super.animateSize,
    super.hapticOn,
    super.announceSemantics,
    super.rethrowErrors,
    required Widget icon,
    required Widget label,
  }) : _variant = .primary,
       super(icon: icon, child: label);

  const FilledAsyncButton.tonalIcon({
    super.key,
    required super.onPressed,
    super.onLongPress,
    super.onHover,
    super.onFocusChange,
    super.style,
    super.focusNode,
    super.autofocus,
    super.clipBehavior,
    super.statesController,
    super.iconAlignment,
    super.controller,
    super.onSuccess,
    super.onError,
    super.onStateChanged,
    super.confirmBeforePress,
    super.loadingChild,
    super.successChild,
    super.errorChild,
    super.disabled,
    super.switchDuration,
    super.transitionBuilder,
    super.successDisplayDuration,
    super.errorDisplayDuration,
    super.cooldownDuration,
    super.animateSize,
    super.hapticOn,
    super.announceSemantics,
    super.rethrowErrors,
    required Widget icon,
    required Widget label,
  }) : _variant = .tonal,
       super(icon: icon, child: label);

  final _FilledVariant _variant;

  @override
  Widget build(BuildContext context) {
    return AsyncButton(
      onPressed: onPressed,
      controller: controller,
      onSuccess: onSuccess,
      onError: onError,
      onStateChanged: onStateChanged,
      confirmBeforePress: confirmBeforePress,
      loadingChild: loadingChild,
      successChild: successChild,
      errorChild: errorChild,
      disabled: disabled,
      switchDuration: switchDuration,
      transitionBuilder: transitionBuilder,
      successDisplayDuration: successDisplayDuration,
      errorDisplayDuration: errorDisplayDuration,
      cooldownDuration: cooldownDuration,
      animateSize: animateSize,
      hapticOn: hapticOn,
      announceSemantics: announceSemantics,
      rethrowErrors: rethrowErrors,
      builder: (context, animatedChild, callback, status) {
        final clip = clipBehavior ?? .none;
        final longPress = callback == null ? null : onLongPress;
        if (_icon != null) {
          return switch (_variant) {
            .primary => FilledButton.icon(
              onPressed: callback,
              onLongPress: longPress,
              onHover: onHover,
              onFocusChange: onFocusChange,
              style: style,
              focusNode: focusNode,
              autofocus: autofocus,
              clipBehavior: clip,
              statesController: statesController,
              iconAlignment: _iconAlignment,
              icon: _icon,
              label: animatedChild,
            ),
            .tonal => FilledButton.tonalIcon(
              onPressed: callback,
              onLongPress: longPress,
              onHover: onHover,
              onFocusChange: onFocusChange,
              style: style,
              focusNode: focusNode,
              autofocus: autofocus,
              clipBehavior: clip,
              statesController: statesController,
              iconAlignment: _iconAlignment,
              icon: _icon,
              label: animatedChild,
            ),
          };
        }
        return switch (_variant) {
          .primary => FilledButton(
            onPressed: callback,
            onLongPress: longPress,
            onHover: onHover,
            onFocusChange: onFocusChange,
            style: style,
            focusNode: focusNode,
            autofocus: autofocus,
            clipBehavior: clip,
            statesController: statesController,
            child: animatedChild,
          ),
          .tonal => FilledButton.tonal(
            onPressed: callback,
            onLongPress: longPress,
            onHover: onHover,
            onFocusChange: onFocusChange,
            style: style,
            focusNode: focusNode,
            autofocus: autofocus,
            clipBehavior: clip,
            statesController: statesController,
            child: animatedChild,
          ),
        };
      },
      child: child,
    );
  }
}
