part of '../../material_async_button.dart';

enum _IconVariant { standard, filled, filledTonal, outlined }

/// Async-aware [IconButton]. Includes all four Material 3 flavors:
/// [IconAsyncButton.new], [IconAsyncButton.filled],
/// [IconAsyncButton.filledTonal], [IconAsyncButton.outlined].
///
/// The [icon] is swapped with `loadingChild`/`successChild`/`errorChild`
/// during the corresponding state.
class IconAsyncButton extends AsyncMaterialButton {
  const IconAsyncButton({
    super.key,
    required super.onPressed,
    super.controller,
    super.onSuccess,
    super.onError,
    super.onStateChanged,
    super.confirmBeforePress,
    super.loadingChild,
    super.successChild,
    super.errorChild,
    super.disabled,
    super.switchDuration,
    super.transitionBuilder,
    super.successDisplayDuration,
    super.errorDisplayDuration,
    super.cooldownDuration,
    super.animateSize,
    super.hapticOn,
    super.announceSemantics,
    super.rethrowErrors,
    required this.icon,
    this.iconSize,
    this.visualDensity,
    this.padding,
    this.alignment,
    this.splashRadius,
    this.color,
    this.focusColor,
    this.hoverColor,
    this.highlightColor,
    this.splashColor,
    this.disabledColor,
    this.mouseCursor,
    this.focusNode,
    this.autofocus = false,
    this.tooltip,
    this.enableFeedback,
    this.constraints,
    this.style,
    this.isSelected,
    this.selectedIcon,
  }) : _variant = .standard,
       super(child: icon);

  const IconAsyncButton.filled({
    super.key,
    required super.onPressed,
    super.controller,
    super.onSuccess,
    super.onError,
    super.onStateChanged,
    super.confirmBeforePress,
    super.loadingChild,
    super.successChild,
    super.errorChild,
    super.disabled,
    super.switchDuration,
    super.transitionBuilder,
    super.successDisplayDuration,
    super.errorDisplayDuration,
    super.cooldownDuration,
    super.animateSize,
    super.hapticOn,
    super.announceSemantics,
    super.rethrowErrors,
    required this.icon,
    this.iconSize,
    this.visualDensity,
    this.padding,
    this.alignment,
    this.splashRadius,
    this.color,
    this.focusColor,
    this.hoverColor,
    this.highlightColor,
    this.splashColor,
    this.disabledColor,
    this.mouseCursor,
    this.focusNode,
    this.autofocus = false,
    this.tooltip,
    this.enableFeedback,
    this.constraints,
    this.style,
    this.isSelected,
    this.selectedIcon,
  }) : _variant = .filled,
       super(child: icon);

  const IconAsyncButton.filledTonal({
    super.key,
    required super.onPressed,
    super.controller,
    super.onSuccess,
    super.onError,
    super.onStateChanged,
    super.confirmBeforePress,
    super.loadingChild,
    super.successChild,
    super.errorChild,
    super.disabled,
    super.switchDuration,
    super.transitionBuilder,
    super.successDisplayDuration,
    super.errorDisplayDuration,
    super.cooldownDuration,
    super.animateSize,
    super.hapticOn,
    super.announceSemantics,
    super.rethrowErrors,
    required this.icon,
    this.iconSize,
    this.visualDensity,
    this.padding,
    this.alignment,
    this.splashRadius,
    this.color,
    this.focusColor,
    this.hoverColor,
    this.highlightColor,
    this.splashColor,
    this.disabledColor,
    this.mouseCursor,
    this.focusNode,
    this.autofocus = false,
    this.tooltip,
    this.enableFeedback,
    this.constraints,
    this.style,
    this.isSelected,
    this.selectedIcon,
  }) : _variant = .filledTonal,
       super(child: icon);

  const IconAsyncButton.outlined({
    super.key,
    required super.onPressed,
    super.controller,
    super.onSuccess,
    super.onError,
    super.onStateChanged,
    super.confirmBeforePress,
    super.loadingChild,
    super.successChild,
    super.errorChild,
    super.disabled,
    super.switchDuration,
    super.transitionBuilder,
    super.successDisplayDuration,
    super.errorDisplayDuration,
    super.cooldownDuration,
    super.animateSize,
    super.hapticOn,
    super.announceSemantics,
    super.rethrowErrors,
    required this.icon,
    this.iconSize,
    this.visualDensity,
    this.padding,
    this.alignment,
    this.splashRadius,
    this.color,
    this.focusColor,
    this.hoverColor,
    this.highlightColor,
    this.splashColor,
    this.disabledColor,
    this.mouseCursor,
    this.focusNode,
    this.autofocus = false,
    this.tooltip,
    this.enableFeedback,
    this.constraints,
    this.style,
    this.isSelected,
    this.selectedIcon,
  }) : _variant = .outlined,
       super(child: icon);

  final Widget icon;
  final double? iconSize;
  final VisualDensity? visualDensity;
  final EdgeInsetsGeometry? padding;
  final AlignmentGeometry? alignment;
  final double? splashRadius;
  final Color? color;
  final Color? focusColor;
  final Color? hoverColor;
  final Color? highlightColor;
  final Color? splashColor;
  final Color? disabledColor;
  final MouseCursor? mouseCursor;
  final FocusNode? focusNode;
  final bool autofocus;
  final String? tooltip;
  final bool? enableFeedback;
  final BoxConstraints? constraints;
  final ButtonStyle? style;
  final bool? isSelected;
  final Widget? selectedIcon;
  final _IconVariant _variant;

  @override
  Widget build(BuildContext context) {
    return AsyncButton(
      onPressed: onPressed,
      controller: controller,
      onSuccess: onSuccess,
      onError: onError,
      onStateChanged: onStateChanged,
      confirmBeforePress: confirmBeforePress,
      loadingChild: loadingChild,
      successChild: successChild,
      errorChild: errorChild,
      disabled: disabled,
      switchDuration: switchDuration,
      transitionBuilder: transitionBuilder,
      successDisplayDuration: successDisplayDuration,
      errorDisplayDuration: errorDisplayDuration,
      cooldownDuration: cooldownDuration,
      animateSize: animateSize,
      hapticOn: hapticOn,
      announceSemantics: announceSemantics,
      rethrowErrors: rethrowErrors,
      builder: (context, child, callback, status) {
        return switch (_variant) {
          .standard => IconButton(
            onPressed: callback,
            icon: child,
            iconSize: iconSize,
            visualDensity: visualDensity,
            padding: padding,
            alignment: alignment,
            splashRadius: splashRadius,
            color: color,
            focusColor: focusColor,
            hoverColor: hoverColor,
            highlightColor: highlightColor,
            splashColor: splashColor,
            disabledColor: disabledColor,
            mouseCursor: mouseCursor,
            focusNode: focusNode,
            autofocus: autofocus,
            tooltip: tooltip,
            enableFeedback: enableFeedback,
            constraints: constraints,
            style: style,
            isSelected: isSelected,
            selectedIcon: selectedIcon,
          ),
          .filled => IconButton.filled(
            onPressed: callback,
            icon: child,
            iconSize: iconSize,
            visualDensity: visualDensity,
            padding: padding,
            alignment: alignment,
            splashRadius: splashRadius,
            color: color,
            focusColor: focusColor,
            hoverColor: hoverColor,
            highlightColor: highlightColor,
            splashColor: splashColor,
            disabledColor: disabledColor,
            mouseCursor: mouseCursor,
            focusNode: focusNode,
            autofocus: autofocus,
            tooltip: tooltip,
            enableFeedback: enableFeedback,
            constraints: constraints,
            style: style,
            isSelected: isSelected,
            selectedIcon: selectedIcon,
          ),
          .filledTonal => IconButton.filledTonal(
            onPressed: callback,
            icon: child,
            iconSize: iconSize,
            visualDensity: visualDensity,
            padding: padding,
            alignment: alignment,
            splashRadius: splashRadius,
            color: color,
            focusColor: focusColor,
            hoverColor: hoverColor,
            highlightColor: highlightColor,
            splashColor: splashColor,
            disabledColor: disabledColor,
            mouseCursor: mouseCursor,
            focusNode: focusNode,
            autofocus: autofocus,
            tooltip: tooltip,
            enableFeedback: enableFeedback,
            constraints: constraints,
            style: style,
            isSelected: isSelected,
            selectedIcon: selectedIcon,
          ),
          .outlined => IconButton.outlined(
            onPressed: callback,
            icon: child,
            iconSize: iconSize,
            visualDensity: visualDensity,
            padding: padding,
            alignment: alignment,
            splashRadius: splashRadius,
            color: color,
            focusColor: focusColor,
            hoverColor: hoverColor,
            highlightColor: highlightColor,
            splashColor: splashColor,
            disabledColor: disabledColor,
            mouseCursor: mouseCursor,
            focusNode: focusNode,
            autofocus: autofocus,
            tooltip: tooltip,
            enableFeedback: enableFeedback,
            constraints: constraints,
            style: style,
            isSelected: isSelected,
            selectedIcon: selectedIcon,
          ),
        };
      },
      child: icon,
    );
  }
}
